### ISSUE TITLE
Set group name command

### ISSUE THREAD

**Issue by samerbes** [PrajjwalDatir/Kaoi#94] opened 2021-09-24 18:10 UTC

**Comment by princeprag** [comment] 2021-10-02 04:49
@PrajjwalDatir can i work on it under HF?

**Comment by princeprag** [comment] 2021-10-02 12:24
@PrajjwalDatir ??

**Comment by PrajjwalDatir** [comment] 2021-10-02 13:12
Sorry for the late reply.
This issue is a duplicate of #29 
Which is already assigned.
You can have a look at #20

**Closed by PrajjwalDatir** 2021-10-02 13:12 UTC
Labels: good first issue, command Request, Hacktoberfest
