### ISSUE TITLE
Enhanced and command request

### ISSUE THREAD

**Issue by PabloChocobar69** [PrajjwalDatir/Kaoi#12] opened 2021-07-30 22:03 UTC
The Bot has been performing great. I would like to request some useful features and some enhancement to the existing one that would help the bot even further.

1. /add - To add a given number in a group chat by the Admins.

2. /grouplink - Mainly to fetch group link of a group by other group members (Non-Admins) who can't add a fellow as they are not admins and saves time for admins to add them manually. (Bot needs to be admins of the respective group). Description of group might not have grouplink as for security reasons and using the command will let users know who's asking for rhe link. 

3.  Tweak to /everyone - A slight modification to existing /everyone command to even enable the MODs to use this command if they aren't the group admin of a particular group where the bot is added. 

4. /Broadcast - To enable the MODs to make the bot announce any new updates or commits added to the bot directly to the groups & dms where the bot has been added. 

‼️ A LOOPHOLE FIX - The bot kicks the MODs from a group when it's the admin and the MODs number isn't. This might be abused by other members for fun. Kindly also fix this so the bot skips kicking the MODs and a message displays like " Skipped, Can't kick  my super-owner!".

‼️ A LOOPHOLE FIX - /purge make the bot exit the group chat in between the process or at the very beginning itself.

Cheers to the developer!

**Comment by PrajjwalDatir** [comment] 2021-08-24 16:37
Duplicate of #33 
Duplicate of #32 
Duplicate of #31 

your 3rd request won't be fulfilled.

**Closed by PrajjwalDatir** 2021-08-24 16:37 UTC
