### ISSUE TITLE
Gif Sticker issue 

### ISSUE THREAD

**Issue by iamherok** [PrajjwalDatir/Kaoi#97] opened 2021-09-25 01:35 UTC
The gif sticker fracture is not working properly

**Comment by PrajjwalDatir** [comment] 2021-09-25 07:41
Can you please provide the screenshot of the sticker and original gif?

**Comment by Whatup364** [comment] 2021-09-27 13:55
I also have same issue

**Comment by Whatup364** [comment] 2021-09-27 14:37
https://www.mediafire.com/file/9253slvbo1jqxcb/Record_2021-09-27-19-26-55_9fcd5e8691ecf6998421ed853039a579.mp4/file

Here is a video link for proof

**Comment by Whatup364** [comment] 2021-09-27 14:38
![Screenshot_2021-09-27-20-08-26-61_9fcd5e8691ecf6998421ed853039a579](https://user-images.githubusercontent.com/89797110/134930368-74b81df7-91ff-4331-a23e-783173373dbc.jpg)
Ss proof

**Comment by Whatup364** [comment] 2021-09-27 14:40
@PrajjwalDatir

**Comment by PrajjwalDatir** [comment] 2021-09-28 07:18
Ok. Thank you for reporting the issue. We'll start working on it.

@aceu1 @ShinNouzen @alensaito1 @Hiroto77 @Nakshatra4762  @SimpFreakin
Any ideas?

**Comment by AlenSaito1** [comment] 2021-09-28 10:41
Can confirm, caused by [WSF](https://github.com/AlenSaito1/wa-sticker-formatter). Blocked by https://github.com/lovell/sharp/pull/2789

**Comment by PrajjwalDatir** [comment] 2021-09-28 12:23
Okay. we will wait till it's merged.

**Comment by Whatup364** [comment] 2021-10-01 03:26
![Screenshot_2021-10-01-08-55-10-26_9fcd5e8691ecf6998421ed853039a579](https://user-images.githubusercontent.com/89797110/135560697-caac8f9b-59ea-450c-bf77-1dd6d1261cfe.jpg)

Wow new problem with gif sticker @PrajjwalDatir

**Comment by PrajjwalDatir** [comment] 2021-10-01 16:25
@Whatup364 
So basically sticker is blank?
Can you tell us, how to reproduce this error?
Does it occur for lengthy GIFs, or for all GIFs?

**Comment by Whatup364** [comment] 2021-10-01 18:00
Old error is back 😭

**Comment by Whatup364** [comment] 2021-10-01 18:01
That error is gone

**Comment by Whatup364** [comment] 2021-10-01 18:03
I just check what you said it is lengthy gif problem

**Comment by Whatup364** [comment] 2021-10-01 18:04
Sorry for inconvenience

**Comment by Whatup364** [comment] 2021-10-01 18:05
I am really sorry

**Comment by PrajjwalDatir** [comment] 2021-10-01 18:10
> I just check what you said it is lengthy gif problem

Ok no problem! Thank you

**Closed** 2021-12-09 02:14 UTC
Labels: bug, enhancement, Hacktoberfest, no-issue-activity
